[package]
name = "graph_layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.10"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
